apiVersion: v1
kind: Pod
metadata:
  name: busybox-ronnielao
  namespace: default
spec:
  containers:
  - image: ronnieclao/cit270
    volumeMounts:
    - name: ssl
      mountPath: "/usr/src/app/ssl"
    command: ["npm"]
    args: ["run", "start"]
    resources:
      requests:
        cpu: 0.125
        memory: 500Mi
      limits:
        cpu: 0.125
        memory: 600Mi
    imagePullPolicy: IfNotPresent
    name: busybox-ronnielao
  volumes:
  - name: ssl
    secret: 
      secretName: ssl.secret.ronnielao
  restartPolicy: Always